### ISSUE TITLE
sysdig-agent is invalid

### ISSUE THREAD

**Issue by baldwinSPC** [draios/sysdig-cloud-scripts#4]
Using the file daemonset yaml found in this repo with only an update to the access key I get the following upon import: 

```
$ kubectl create -f sysdig.yml
The DaemonSet "sysdig-agent" is invalid.
spec.template.metadata.labels: Invalid value: null: `selector` does not match template `labels`
```

**Comment by stewartshea** [comment]
@baldwinSPC I was able to get the file to take by adding the label in the template section as well. Mine was slightly modified, and looks like: 


apiVersion: extensions/v1beta1
kind: DaemonSet                     
metadata:
  name: sysdigagent
spec:
  template:
    metadata:
      labels: 
        name: sysdigagent
    spec:
...

**Comment by ltagliamonte** [comment]
fixed with https://github.com/draios/sysdig-cloud-scripts/pull/5 -  Closing issue

**Comment by baldwinSPC** [comment]
Cool. Confirmed fixed. I'll add it to https://stackpoint.io this week.
